spring:
  datasource:
    url: jdbc:postgresql://{DB_HOST:localhost}:${DB_PORT:5432}/${db_NAME:chatdb}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20 # Maximum number of connections in the pool
      minimum-idle: 5 # Minimum number of idle connections in the pool
      connection-timeout: 20000 # Maximum time to wait for a connection from the pool
      idle-timeout: 300000 # Maximum time a connection can be idle in the pool
      max-lifetime: 1200000 # Maximum lifetime of a connection in the pool


  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
    com.thongho.chatapp: INFO

  