spring:
  application:
    name: chat-application

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show_sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true # This is useful for existing databases

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms # 2 seconds
    lettuce: # Use Lettuce as the Redis client
      pool:
        max-active: 8 # Maximum number of active connections
        max-idle: 8 # Maximum number of idle connections in the pool
        min-idle: 0


  mail:
    host: ${MAIL_HOST:smtp.example.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always # Include error messages in the response
    include-binding-errors: always # Include binding errors in the response

jwt:
  secret: ${JWT_SECRET: RhlRA2BNgj1xRlBz1GQgVI3JoGilJTKgTpSA6gmHhdw=}
  expriration: 86400000 # 1 day in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:4200}
  email:
    verification:
      expiration: 86400000 # 24 hours
    from: ${EMAIL_FROM:noreply@chatapp.com}

logging:
  level:
    root: INFO
    com.thongho.chatapplication: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    # file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"